from __future__ import annotations
import csv
import gzip
import json
import os
from pathlib import Path
from typing import Any

from core.types import ExportFormat, GeneratedDataset


def export(
    dataset: GeneratedDataset,
    fmt: ExportFormat,
    output_dir: str = "./output",
    filename: str | None = None,
    compress: bool = False,
) -> str:
    """
    GeneratedDataset'i belirtilen formata kaydeder.
    Kaydedilen dosyanın yolunu döner.
    """
    Path(output_dir).mkdir(parents=True, exist_ok=True)

    base_name = filename or dataset.spec.name
    ext = fmt.value
    path = os.path.join(output_dir, f"{base_name}.{ext}")

    records = dataset.records

    if fmt == ExportFormat.CSV:
        _to_csv(records, path)
    elif fmt == ExportFormat.JSONL:
        _to_jsonl(records, path)
    elif fmt == ExportFormat.PARQUET:
        _to_parquet(records, path)
    elif fmt == ExportFormat.TXT:
        _to_txt(records, dataset.spec, path)
    elif fmt == ExportFormat.SQL:
        _to_sql(records, dataset.spec, path)
    elif fmt == ExportFormat.XLSX:
        _to_xlsx(records, path)
    else:
        raise ValueError(f"Desteklenmeyen format: {fmt}")

    # Compress if requested
    if compress:
        path = _compress_file(path)

    # Write metadata file
    _write_metadata(dataset, path)

    size_kb = os.path.getsize(path) / 1024
    print(f"[exporter] ✓ {path} ({len(records)} kayıt, {size_kb:.1f} KB)")
    return path


def _to_csv(records: list[dict], path: str) -> None:
    if not records:
        Path(path).touch()
        return
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=records[0].keys())
        writer.writeheader()
        writer.writerows(records)


def _to_jsonl(records: list[dict], path: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        for record in records:
            f.write(json.dumps(record, ensure_ascii=False, default=str) + "\n")


def _to_parquet(records: list[dict], path: str) -> None:
    try:
        import pandas as pd
        df = pd.DataFrame(records)
        df.to_parquet(path, index=False)
    except ImportError:
        # pandas/pyarrow yoksa JSONL'e düş
        fallback = path.replace(".parquet", ".jsonl")
        print(f"[exporter] pandas/pyarrow bulunamadı, JSONL'e düşülüyor: {fallback}")
        _to_jsonl(records, fallback)
        return


def _to_txt(records: list[dict], spec: Any, path: str) -> None:
    """NLP veri setleri için düz metin çıktısı."""
    with open(path, "w", encoding="utf-8") as f:
        for i, record in enumerate(records, 1):
            # Her kaydı alan adı olmadan tek blok yaz (metin verisi için)
            text_fields = [
                str(v)
                for k, v in record.items()
                if isinstance(v, str) and len(str(v)) > 20
            ]
            if text_fields:
                f.write("\n".join(text_fields) + "\n\n---\n\n")
            else:
                f.write(json.dumps(record, ensure_ascii=False, default=str) + "\n")


def _to_sql(records: list[dict], spec: Any, path: str) -> None:
    """SQL INSERT statements olarak export et."""
    if not records:
        Path(path).touch()
        return
    
    table_name = spec.name
    columns = list(records[0].keys())
    
    with open(path, "w", encoding="utf-8") as f:
        # CREATE TABLE statement
        f.write(f"-- Generated by SynthForge\n")
        f.write(f"-- Table: {table_name}\n")
        f.write(f"-- Records: {len(records)}\n\n")
        
        # Generate CREATE TABLE
        col_defs = []
        for field in spec.fields:
            sql_type = _python_to_sql_type(field.dtype)
            nullable = "" if field.nullable else " NOT NULL"
            unique = " UNIQUE" if field.unique else ""
            col_defs.append(f"    {field.name} {sql_type}{nullable}{unique}")
        
        f.write(f"CREATE TABLE IF NOT EXISTS {table_name} (\n")
        f.write(",\n".join(col_defs))
        f.write("\n);\n\n")
        
        # Generate INSERT statements (batch of 100)
        batch_size = 100
        for i in range(0, len(records), batch_size):
            batch = records[i:i + batch_size]
            
            f.write(f"INSERT INTO {table_name} ({', '.join(columns)}) VALUES\n")
            
            values = []
            for record in batch:
                row_values = []
                for col in columns:
                    val = record.get(col)
                    row_values.append(_sql_value(val))
                values.append(f"    ({', '.join(row_values)})")
            
            f.write(",\n".join(values))
            f.write(";\n\n")


def _python_to_sql_type(dtype: str) -> str:
    """Python dtype'ı SQL type'a çevir."""
    mapping = {
        "int": "INTEGER",
        "float": "REAL",
        "str": "TEXT",
        "bool": "BOOLEAN",
        "datetime": "TIMESTAMP",
        "category": "TEXT",
    }
    return mapping.get(dtype, "TEXT")


def _sql_value(val: Any) -> str:
    """Python değerini SQL değerine çevir."""
    if val is None:
        return "NULL"
    if isinstance(val, bool):
        return "TRUE" if val else "FALSE"
    if isinstance(val, (int, float)):
        return str(val)
    # String değerleri escape et
    escaped = str(val).replace("'", "''")
    return f"'{escaped}'"


def _to_xlsx(records: list[dict], path: str) -> None:
    """Excel formatında export et."""
    try:
        import pandas as pd
        df = pd.DataFrame(records)
        df.to_excel(path, index=False, engine="openpyxl")
    except ImportError:
        # openpyxl yoksa CSV'ye düş
        fallback = path.replace(".xlsx", ".csv")
        print(f"[exporter] openpyxl bulunamadı, CSV'ye düşülüyor: {fallback}")
        _to_csv(records, fallback)


def _compress_file(path: str) -> str:
    """Dosyayı gzip ile sıkıştır."""
    gz_path = path + ".gz"
    with open(path, "rb") as f_in:
        with gzip.open(gz_path, "wb") as f_out:
            f_out.writelines(f_in)
    os.remove(path)  # Orijinal dosyayı sil
    return gz_path


def _write_metadata(dataset: GeneratedDataset, data_path: str) -> None:
    """Metadata dosyası yaz."""
    import dataclasses
    from datetime import datetime
    
    meta_path = data_path.rsplit(".", 1)[0] + "_meta.json"
    
    metadata = {
        "generated_at": datetime.now().isoformat(),
        "generator": dataset.metadata.get("generator", "unknown"),
        "record_count": len(dataset.records),
        "spec": {
            "name": dataset.spec.name,
            "data_type": dataset.spec.data_type.value,
            "locale": dataset.spec.locale,
            "field_count": len(dataset.spec.fields),
            "fields": [
                {"name": f.name, "dtype": f.dtype}
                for f in dataset.spec.fields
            ],
        },
        **dataset.metadata,
    }
    
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, ensure_ascii=False, indent=2)
